// Site configuration, sourced from the committed site vault snapshot
// (content/config/site.json, generated by `npm run sync` from the canonical
// Obsidian vault's Config/site.json). Edit the vault's Config/site.json to
// change identity, navigation, traces, or homepage sections — never Astro code.

import siteConfig from "./site.json";

interface NavLink {
	label: string;
	href: string;
}

export interface TraceConfig {
	id: string;
	label: string;
	/** Content collection that feeds the trace (writing | projects | shelf). */
	source: string;
	visible?: boolean;
}

type SiteConfig = typeof siteConfig;

const cfg: SiteConfig = siteConfig;

export interface HomeSection {
	key: string;
	/** Number of items to show, or `null` for all. Used for "selected/first N". */
	limit: number | null;
}

export const site = {
	name: cfg.name,
	title: cfg.title,
	description: cfg.description,
	url: cfg.url,
	email: cfg.email,
	location: cfg.location,
	bio: cfg.bio,
	social: cfg.social,
};

export const nav: NavLink[] = cfg.nav;

/** Ordered homepage sections, each maybe bounded by a `limit`. */
export const homeSections: string[] =
	cfg.homepage?.sections ?? (cfg as { homeSections?: string[] }).homeSections ?? [
		"github",
		"work",
		"projects",
		"writing",
	];
// Back-compat: allow `homepage.sections` entries that are either plain keys or
// `"key:limit"` strings (e.g. "selected_work:2") resolved into booleans/limits.
export function resolveHomeSection(section: string): HomeSection {
	const [key, rawLimit] = section.split(":");
	const limit = rawLimit ? Number(rawLimit) || null : null;
	return { key: key.trim(), limit };
}

/** Traces (WRITE/BUILD/READ) rendered on the YASH page; fully config-driven. */
export const traces: TraceConfig[] = cfg.traces ?? [];

export const homepage = cfg.homepage;